import { useRouter } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppHeader, EmptyState, LoadingView, StatusPill } from "@/components/study-ui";
import { ScreenContainer } from "@/components/screen-container";
import { appTheme } from "@/lib/app-theme";
import { useStudy } from "@/lib/study-context";
import { buildSubjectFollowUps, type SubjectFollowUpStatus } from "@/lib/subject-follow-up";

const statusLabel: Record<SubjectFollowUpStatus, string> = { critical: "يحتاج أولوية", attention: "يحتاج متابعة", "on-track": "ضمن المسار", unplanned: "بلا هدف" };
const statusTone: Record<SubjectFollowUpStatus, "warning" | "success" | "neutral"> = { critical: "warning", attention: "warning", "on-track": "success", unplanned: "neutral" };

export default function FollowUpScreen() {
  const router = useRouter();
  const { hydrated, subjects, subjectGoals, lectures, reviewCards, reviewSessions, tasks } = useStudy();
  if (!hydrated) return <ScreenContainer><LoadingView /></ScreenContainer>;
  const items = buildSubjectFollowUps({ subjects, subjectGoals, lectures, reviewCards, reviewSessions, tasks });
  const needsAttention = items.filter((item) => item.status !== "on-track").length;
  return <ScreenContainer className="px-5"><AppHeader eyebrow="ترتيب محلي بحسب فجوة الهدف" title="متابعة المواد" action={<Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>رجوع</Text></Pressable>} /><FlatList data={items} keyExtractor={(item) => item.subject.id} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.summary}><View style={styles.summaryIcon}><Text style={styles.summaryNumber}>{needsAttention}</Text></View><View style={styles.copy}><Text style={styles.summaryTitle}>مواد تحتاج متابعة</Text><Text style={styles.summaryText}>ترتيب من الأقل تقدماً إلى الأقرب لإكمال هدف الترم. الحساب محلي من محاضراتك ومراجعتك وتركيزك.</Text></View></View>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/subject/[subjectId]", params: { subjectId: item.subject.id } })} style={styles.card}><View style={[styles.colorDot, { backgroundColor: item.subject.color }]} /><View style={styles.copy}><View style={styles.cardHeader}><Text style={styles.subjectTitle}>{item.subject.title}</Text><StatusPill label={statusLabel[item.status]} tone={statusTone[item.status]} /></View><Text style={styles.reason}>{item.reason}</Text><View style={styles.track}><View style={[styles.fill, { width: `${item.percent}%` }]} /></View><Text style={styles.meta}>{item.goal ? `${item.percent}% من هدف الترم · ${item.progress.lectureCount} محاضرات · ${item.progress.focusMinutes} د تركيز` : "افتح المادة وحدد هدفاً قابلاً للقياس"}</Text></View></Pressable>} ListEmptyComponent={<EmptyState icon="insights" title="أضف موادك أولاً" description="ستظهر هنا قراءة محلية لمتابعة تقدم كل مادة." />} /></ScreenContainer>;
}

const styles = StyleSheet.create({ list: { gap: 10, paddingBottom: 28 }, summary: { alignItems: "center", backgroundColor: "#F5F3FF", borderColor: "#DDD6FE", borderRadius: 19, borderWidth: 1, flexDirection: "row-reverse", gap: 12, marginBottom: 4, padding: 15 }, summaryIcon: { alignItems: "center", backgroundColor: appTheme.violet, borderRadius: 16, height: 50, justifyContent: "center", width: 50 }, summaryNumber: { color: "#FFFFFF", fontSize: 20, fontWeight: "900" }, copy: { flex: 1 }, summaryTitle: { color: appTheme.ink, fontSize: 16, fontWeight: "800", textAlign: "right" }, summaryText: { color: appTheme.muted, fontSize: 11, lineHeight: 17, marginTop: 3, textAlign: "right" }, card: { alignItems: "flex-start", backgroundColor: appTheme.surface, borderColor: appTheme.border, borderRadius: 18, borderWidth: 1, flexDirection: "row-reverse", gap: 10, padding: 14 }, colorDot: { borderRadius: 99, height: 11, marginTop: 5, width: 11 }, cardHeader: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between" }, subjectTitle: { color: appTheme.ink, fontSize: 15, fontWeight: "800", textAlign: "right" }, reason: { color: appTheme.muted, fontSize: 11, marginTop: 4, textAlign: "right" }, track: { backgroundColor: "#EDE9FE", borderRadius: 99, height: 7, marginTop: 10, overflow: "hidden" }, fill: { backgroundColor: appTheme.violet, borderRadius: 99, height: 7 }, meta: { color: appTheme.primary, fontSize: 10, fontWeight: "700", marginTop: 6, textAlign: "right" }, back: { backgroundColor: appTheme.primarySoft, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7 }, backText: { color: appTheme.primary, fontSize: 11, fontWeight: "800" } });
