import { useRouter } from "expo-router";
import { useState } from "react";
import { FlatList, Platform, Pressable, StyleSheet, Text, View } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

import { AppHeader, EmptyState, LoadingView, StatusPill } from "@/components/study-ui";
import { ScreenContainer } from "@/components/screen-container";
import { appTheme } from "@/lib/app-theme";
import { useStudy } from "@/lib/study-context";
import { buildSubjectFollowUps, filterSubjectFollowUpsByTerm, type SubjectFollowUpStatus } from "@/lib/subject-follow-up";
import { createSubjectFollowUpReportHtml } from "@/lib/subject-follow-up-report";

const statusLabel: Record<SubjectFollowUpStatus, string> = { critical: "يحتاج أولوية", attention: "يحتاج متابعة", "on-track": "ضمن المسار", unplanned: "بلا هدف" };
const statusTone: Record<SubjectFollowUpStatus, "warning" | "success" | "neutral"> = { critical: "warning", attention: "warning", "on-track": "success", unplanned: "neutral" };

export default function FollowUpScreen() {
  const router = useRouter();
  const { hydrated, subjects, terms, subjectGoals, lectures, reviewCards, reviewSessions, tasks } = useStudy();
  const [termId, setTermId] = useState<string | undefined>();
  const [exporting, setExporting] = useState(false);
  if (!hydrated) return <ScreenContainer><LoadingView /></ScreenContainer>;
  const allItems = buildSubjectFollowUps({ subjects, subjectGoals, lectures, reviewCards, reviewSessions, tasks });
  const items = filterSubjectFollowUpsByTerm(allItems, termId);
  const needsAttention = items.filter((item) => item.status !== "on-track").length;
  const filterLabel = termId ? terms.find((term) => term.id === termId)?.title ?? "ترم محدد" : "كل الترمين";
  const exportReport = async () => { if (exporting) return; setExporting(true); try { const html = createSubjectFollowUpReportHtml({ items, filterLabel }); if (Platform.OS === "web") { await Print.printAsync({ html }); return; } const { uri } = await Print.printToFileAsync({ html }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { UTI: ".pdf", mimeType: "application/pdf", dialogTitle: "مشاركة تقرير متابعة المواد" }); } finally { setExporting(false); } };
  return <ScreenContainer className="px-5"><AppHeader eyebrow="ترتيب محلي بحسب فجوة الهدف" title="متابعة المواد" action={<Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>رجوع</Text></Pressable>} /><FlatList data={items} keyExtractor={(item) => item.subject.id} contentContainerStyle={styles.list} ListHeaderComponent={<><View style={styles.summary}><View style={styles.summaryIcon}><Text style={styles.summaryNumber}>{needsAttention}</Text></View><View style={styles.copy}><Text style={styles.summaryTitle}>مواد تحتاج متابعة</Text><Text style={styles.summaryText}>ترتيب من الأقل تقدماً إلى الأقرب لإكمال هدف الترم. الحساب محلي من محاضراتك ومراجعتك وتركيزك.</Text></View></View>{terms.length ? <View style={styles.termFilter}><Text style={styles.filterLabel}>الترم</Text><View style={styles.chips}><Pressable onPress={() => setTermId(undefined)} style={[styles.chip, !termId && styles.chipActive]}><Text style={[styles.chipText, !termId && styles.chipTextActive]}>الكل</Text></Pressable>{terms.map((term) => <Pressable key={term.id} onPress={() => setTermId(term.id)} style={[styles.chip, termId === term.id && styles.chipActive]}><Text style={[styles.chipText, termId === term.id && styles.chipTextActive]}>{term.title}</Text></Pressable>)}</View></View> : null}<Pressable disabled={exporting} onPress={() => void exportReport()} style={[styles.exportButton, exporting && styles.disabled]}><Text style={styles.exportText}>{exporting ? "يجري إنشاء التقرير" : "تصدير تقرير المتابعة PDF"}</Text></Pressable></>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/subject/[subjectId]", params: { subjectId: item.subject.id } })} style={styles.card}><View style={[styles.colorDot, { backgroundColor: item.subject.color }]} /><View style={styles.copy}><View style={styles.cardHeader}><Text style={styles.subjectTitle}>{item.subject.title}</Text><StatusPill label={statusLabel[item.status]} tone={statusTone[item.status]} /></View><Text style={styles.reason}>{item.reason}</Text><View style={styles.track}><View style={[styles.fill, { width: `${item.percent}%` }]} /></View><Text style={styles.meta}>{item.goal ? `${item.percent}% من هدف الترم · ${item.progress.lectureCount} محاضرات · ${item.progress.focusMinutes} د تركيز` : "افتح المادة وحدد هدفاً قابلاً للقياس"}</Text></View></Pressable>} ListEmptyComponent={<EmptyState icon="insights" title={termId ? "لا مواد في هذا الترم" : "أضف موادك أولاً"} description={termId ? "اختر ترماً آخر أو أضف مادة لهذا الترم." : "ستظهر هنا قراءة محلية لمتابعة تقدم كل مادة."} />} /></ScreenContainer>;
}

const styles = StyleSheet.create({ list: { gap: 10, paddingBottom: 28 }, summary: { alignItems: "center", backgroundColor: "#F5F3FF", borderColor: "#DDD6FE", borderRadius: 19, borderWidth: 1, flexDirection: "row-reverse", gap: 12, marginBottom: 4, padding: 15 }, summaryIcon: { alignItems: "center", backgroundColor: appTheme.violet, borderRadius: 16, height: 50, justifyContent: "center", width: 50 }, summaryNumber: { color: "#FFFFFF", fontSize: 20, fontWeight: "900" }, copy: { flex: 1 }, summaryTitle: { color: appTheme.ink, fontSize: 16, fontWeight: "800", textAlign: "right" }, summaryText: { color: appTheme.muted, fontSize: 11, lineHeight: 17, marginTop: 3, textAlign: "right" }, termFilter: { backgroundColor: appTheme.surface, borderColor: appTheme.border, borderRadius: 15, borderWidth: 1, gap: 9, padding: 12 }, filterLabel: { color: appTheme.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, chips: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, chip: { backgroundColor: "#F1F5F9", borderRadius: 99, paddingHorizontal: 11, paddingVertical: 7 }, chipActive: { backgroundColor: appTheme.primarySoft }, chipText: { color: appTheme.muted, fontSize: 11, fontWeight: "800" }, chipTextActive: { color: appTheme.primary }, exportButton: { alignItems: "center", backgroundColor: appTheme.violet, borderRadius: 13, justifyContent: "center", minHeight: 43 }, exportText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, disabled: { opacity: 0.45 }, card: { alignItems: "flex-start", backgroundColor: appTheme.surface, borderColor: appTheme.border, borderRadius: 18, borderWidth: 1, flexDirection: "row-reverse", gap: 10, padding: 14 }, colorDot: { borderRadius: 99, height: 11, marginTop: 5, width: 11 }, cardHeader: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between" }, subjectTitle: { color: appTheme.ink, fontSize: 15, fontWeight: "800", textAlign: "right" }, reason: { color: appTheme.muted, fontSize: 11, marginTop: 4, textAlign: "right" }, track: { backgroundColor: "#EDE9FE", borderRadius: 99, height: 7, marginTop: 10, overflow: "hidden" }, fill: { backgroundColor: appTheme.violet, borderRadius: 99, height: 7 }, meta: { color: appTheme.primary, fontSize: 10, fontWeight: "700", marginTop: 6, textAlign: "right" }, back: { backgroundColor: appTheme.primarySoft, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7 }, backText: { color: appTheme.primary, fontSize: 11, fontWeight: "800" } });
