import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { PrimaryButton } from "@/components/study-ui";
import { appTheme } from "@/lib/app-theme";
import { getStudyDataImportPreview, importSections, type StudyDataImportPayload, type StudyDataImportPreviewBySection, type StudyDataImportSection } from "@/lib/study-data-import";
import type { StudyStore } from "@/lib/study-types";

const labels: Record<StudyDataImportSection, { title: string; description: string }> = {
  structure: { title: "هيكل الدراسة", description: "السنوات والترم والمواد" },
  lectures: { title: "المحاضرات والنصوص", description: "دون الصوت والمرفقات" },
  review: { title: "المراجعة", description: "البطاقات والجلسات والقوائم" },
  tasks: { title: "الواجبات والخطة", description: "المهام دون تنبيهات النظام" },
};

export function StudyDataImportModal({ visible, fileName, payload, current, selected, busy, onClose, onToggle, onApply }: { visible: boolean; fileName: string; payload: StudyDataImportPayload | null; current: StudyStore; selected: StudyDataImportSection[]; busy: boolean; onClose: () => void; onToggle: (section: StudyDataImportSection) => void; onApply: () => void }) {
  const preview = payload ? getStudyDataImportPreview(current, payload, selected) : undefined;
  const totals = preview ? importSections.reduce((total, section) => ({ additions: total.additions + preview[section].additions, duplicates: total.duplicates + preview[section].duplicates, blocked: total.blocked + preview[section].blocked }), { additions: 0, duplicates: 0, blocked: 0 }) : { additions: 0, duplicates: 0, blocked: 0 };
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><View style={styles.modal}><View style={styles.header}><Pressable onPress={onClose} style={styles.closeButton}><MaterialIcons name="close" size={22} color={appTheme.ink} /></Pressable><Text style={styles.title}>معاينة دمج البيانات</Text><View style={styles.closeButton} /></View><ScrollView contentContainerStyle={styles.content}><View style={styles.notice}><MaterialIcons name="privacy-tip" size={21} color={appTheme.success} /><View style={styles.copy}><Text style={styles.fileName} numberOfLines={1}>{fileName}</Text><Text style={styles.note}>لن تُستبدل بيانات هذا الجهاز، ولا يمكن استعادة ملفات الصوت أو المرفقات من ملف JSON.</Text></View></View><View style={styles.total}><Text style={styles.totalText}>سيُضاف {totals.additions} عنصر</Text><Text style={styles.totalMeta}>{totals.duplicates ? `${totals.duplicates} مكرر` : "لا عناصر مكررة"}{totals.blocked ? ` · ${totals.blocked} يحتاج ارتباطاً` : ""}</Text></View><Text style={styles.instruction}>اختر الفئات، ثم راجع الأثر المتوقع قبل الدمج:</Text>{importSections.map((section) => <PreviewChoice key={section} section={section} selected={selected.includes(section)} preview={preview?.[section]} disabled={busy} onToggle={onToggle} />)}</ScrollView><View style={styles.footer}><PrimaryButton label={busy ? "يجري دمج البيانات" : `دمج ${selected.length} فئات`} icon="merge-type" disabled={!selected.length || busy} onPress={onApply} /></View></View></Modal>;
}

function PreviewChoice({ section, selected, preview, disabled, onToggle }: { section: StudyDataImportSection; selected: boolean; preview?: StudyDataImportPreviewBySection[StudyDataImportSection]; disabled: boolean; onToggle: (section: StudyDataImportSection) => void }) {
  const label = labels[section];
  const summary = preview ? preview.incoming ? `+${preview.additions} إضافة${preview.duplicates ? ` · ${preview.duplicates} مكرر` : ""}${preview.blocked ? ` · ${preview.blocked} غير مرتبط` : ""}` : "لا عناصر في الملف" : "يجري تحضير المعاينة";
  return <Pressable disabled={disabled} onPress={() => onToggle(section)} style={[styles.choice, selected && styles.choiceSelected, disabled && styles.disabled]}><View style={[styles.check, selected && styles.checkSelected]}>{selected ? <MaterialIcons name="check" size={15} color="#FFFFFF" /> : null}</View><View style={styles.copy}><Text style={styles.choiceTitle}>{label.title}</Text><Text style={styles.choiceNote}>{label.description}</Text><Text style={[styles.previewText, !selected && styles.previewTextMuted]}>{summary}</Text></View><MaterialIcons name="chevron-left" size={20} color={appTheme.muted} /></Pressable>;
}

const styles = StyleSheet.create({
  modal: { backgroundColor: appTheme.background, flex: 1 }, header: { alignItems: "center", backgroundColor: appTheme.surface, borderBottomColor: appTheme.border, borderBottomWidth: 1, flexDirection: "row-reverse", justifyContent: "space-between", padding: 18 }, closeButton: { alignItems: "center", height: 38, justifyContent: "center", width: 38 }, title: { color: appTheme.ink, fontSize: 17, fontWeight: "800" }, content: { gap: 10, padding: 18, paddingBottom: 92 }, notice: { alignItems: "flex-start", backgroundColor: appTheme.successSoft, borderRadius: 15, flexDirection: "row-reverse", gap: 10, padding: 13 }, copy: { flex: 1 }, fileName: { color: appTheme.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, note: { color: appTheme.muted, fontSize: 11, lineHeight: 17, marginTop: 3, textAlign: "right" }, total: { backgroundColor: "#F5F3FF", borderColor: "#DDD6FE", borderRadius: 14, borderWidth: 1, flexDirection: "row-reverse", justifyContent: "space-between", padding: 12 }, totalText: { color: appTheme.violet, fontSize: 13, fontWeight: "800" }, totalMeta: { color: appTheme.muted, fontSize: 11, textAlign: "right" }, instruction: { color: appTheme.muted, fontSize: 12, fontWeight: "700", marginTop: 4, textAlign: "right" }, choice: { alignItems: "center", backgroundColor: appTheme.surface, borderColor: appTheme.border, borderRadius: 15, borderWidth: 1, flexDirection: "row-reverse", gap: 10, padding: 13 }, choiceSelected: { backgroundColor: "#F5F3FF", borderColor: appTheme.primary }, check: { alignItems: "center", borderColor: "#CBD5E1", borderRadius: 9, borderWidth: 1, height: 22, justifyContent: "center", width: 22 }, checkSelected: { backgroundColor: appTheme.primary, borderColor: appTheme.primary }, choiceTitle: { color: appTheme.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, choiceNote: { color: appTheme.muted, fontSize: 11, marginTop: 2, textAlign: "right" }, previewText: { color: appTheme.success, fontSize: 11, fontWeight: "800", marginTop: 5, textAlign: "right" }, previewTextMuted: { color: appTheme.muted }, footer: { backgroundColor: appTheme.surface, borderTopColor: appTheme.border, borderTopWidth: 1, bottom: 0, left: 0, padding: 16, position: "absolute", right: 0 }, disabled: { opacity: 0.45 },
});
