import type { ReviewSession, Subject } from "@/lib/study-types";

const MONTH_DAYS = 28;

function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character); }

export function createMonthlyFocusReportHtml({ reviewSessions, subjects, generatedAt = new Date() }: { reviewSessions: ReviewSession[]; subjects: Subject[]; generatedAt?: Date }) {
  const start = new Date(generatedAt); start.setHours(0, 0, 0, 0); start.setDate(start.getDate() - (MONTH_DAYS - 1));
  const sessions = reviewSessions.filter((session) => new Date(session.completedAt).getTime() >= start.getTime());
  const totalMinutes = sessions.reduce((total, session) => total + session.durationMinutes, 0);
  const activeDays = new Set(sessions.map((session) => new Date(session.completedAt).toDateString())).size;
  const averageMinutes = activeDays ? Math.round(totalMinutes / activeDays) : 0;
  const subjectRows = subjects.map((subject) => ({ subject, minutes: sessions.filter((session) => session.subjectId === subject.id).reduce((total, session) => total + session.durationMinutes, 0) })).filter((item) => item.minutes > 0).sort((a, b) => b.minutes - a.minutes).map((item) => `<tr><td>${escapeHtml(item.subject.title)}</td><td>${item.minutes} دقيقة</td></tr>`).join("") || "<tr><td colspan=\"2\">لا توجد جلسات مرتبطة بمادة خلال هذه الفترة.</td></tr>";
  const dailyRows = Array.from({ length: MONTH_DAYS }, (_, index) => { const day = new Date(start); day.setDate(start.getDate() + index); const minutes = sessions.filter((session) => new Date(session.completedAt).toDateString() === day.toDateString()).reduce((total, session) => total + session.durationMinutes, 0); return `<tr><td>${escapeHtml(day.toLocaleDateString("ar"))}</td><td>${minutes} دقيقة</td></tr>`; }).join("");
  return `<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="utf-8"/><style>@page{margin:24px}body{font-family:Arial,sans-serif;color:#172554;direction:rtl}h1{color:#312E81;margin:0 0 6px}.muted{color:#64748B;font-size:12px}.metrics{display:flex;gap:10px;margin:18px 0}.metric{background:#EEF2FF;border-radius:12px;flex:1;padding:12px}.metric strong{display:block;font-size:20px;margin-top:4px}table{width:100%;border-collapse:collapse;margin-top:10px}th{background:#312E81;color:#fff}th,td{border:1px solid #CBD5E1;padding:8px;text-align:right}tr:nth-child(even){background:#F8FAFC}.footer{margin-top:18px;color:#64748B;font-size:11px}</style></head><body><h1>تقرير التركيز الشهري — مُحاضِر</h1><p class="muted">آخر ${MONTH_DAYS} يوماً · أُنشئ محلياً في ${escapeHtml(generatedAt.toLocaleString("ar"))}</p><section class="metrics"><div class="metric">دقائق التركيز<strong>${totalMinutes}</strong></div><div class="metric">جلسات مكتملة<strong>${sessions.length}</strong></div><div class="metric">أيام نشطة<strong>${activeDays}</strong></div><div class="metric">متوسط اليوم النشط<strong>${averageMinutes} د</strong></div></section><h2>التركيز حسب المادة</h2><table><thead><tr><th>المادة</th><th>دقائق التركيز</th></tr></thead><tbody>${subjectRows}</tbody></table><h2>نشاط الأيام</h2><table><thead><tr><th>التاريخ</th><th>دقائق التركيز</th></tr></thead><tbody>${dailyRows}</tbody></table><p class="footer">هذا التقرير يعتمد على جلسات مُحاضِر المحلية فقط، ولا يرسل أي بيانات دراسة عند إنشائه أو مشاركته.</p></body></html>`;
}
