import type { Subject } from "./study-types";
import type { SubjectProgress } from "./subject-progress";
import { progressPercent } from "./subject-progress";

function escapeHtml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }
function row(label: string, current: number, total: number) { return `<tr><td>${label}</td><td>${current} من ${total}</td><td>${progressPercent(current, total)}%</td></tr>`; }

/** تقرير عربي محلي يُنشأ من بيانات المادة الحالية فقط، بلا رفع بيانات أو ملفات وسائط. */
export function createSubjectProgressReportHtml({ subject, progress, createdAt = new Date() }: { subject: Subject; progress: SubjectProgress; createdAt?: Date }) {
  return `<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;color:#172554;padding:28px;direction:rtl}h1{color:#4338CA;margin:0 0 6px}.meta{color:#64748B;font-size:12px;margin-bottom:22px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:18px 0}.card{background:#F5F3FF;border:1px solid #DDD6FE;border-radius:12px;padding:12px}.value{font-size:20px;font-weight:700;color:#4338CA}.label{font-size:12px;color:#475569;margin-top:5px}table{border-collapse:collapse;width:100%;margin-top:14px}th,td{border:1px solid #E2E8F0;padding:10px;text-align:right}th{background:#EEF2FF;color:#3730A3}.privacy{margin-top:24px;border-top:1px solid #E2E8F0;padding-top:12px;color:#64748B;font-size:11px}</style></head><body><h1>تقرير تقدم المادة</h1><div class="meta">${escapeHtml(subject.title)} · ${createdAt.toLocaleDateString("ar")}</div><div class="grid"><div class="card"><div class="value">${progress.lectureCount}</div><div class="label">محاضرات</div></div><div class="card"><div class="value">${progress.recordingMinutes} د</div><div class="label">تسجيل</div></div><div class="card"><div class="value">${progress.focusMinutes} د</div><div class="label">تركيز</div></div></div><table><thead><tr><th>المؤشر</th><th>الإنجاز</th><th>النسبة</th></tr></thead><tbody>${row("تحويل النص", progress.transcribedCount, progress.lectureCount)}${row("تلخيص المحاضرات", progress.summarizedCount, progress.lectureCount)}${row("بطاقات المراجعة", progress.reviewedCardCount, progress.reviewCardCount)}${row("الواجبات", progress.completedTaskCount, progress.taskCount)}</tbody></table><p class="privacy">أُنشئ هذا التقرير محلياً من بيانات جهازك. لا يتضمن ملفات الصوت أو المرفقات.</p></body></html>`;
}
