import { formatFollowUpCompletionTime, type FollowUpSubjectTimingInsight } from "./weekly-reflection-follow-up-timing-insights";

function escapeHtml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }

/** ينشئ تقريراً عربياً محلياً عن أزمنة إتمام وتأجيل خطوات المتابعة بحسب المادة. */
export function createFollowUpTimingReportHtml({ insights, filterLabel = "كل المواد", createdAt = new Date() }: { insights: FollowUpSubjectTimingInsight[]; filterLabel?: string; createdAt?: Date }) {
  const measuredCompletions = insights.reduce((total, item) => total + item.measuredCompletionCount, 0);
  const postponements = insights.reduce((total, item) => total + item.postponementCount, 0);
  const rows = insights.map((item) => `<tr><td>${escapeHtml(item.subject.title)}</td><td>${item.measuredCompletionCount}</td><td>${formatFollowUpCompletionTime(item.averageCompletionHours)}</td><td>${item.postponementCount}</td><td>${item.averagePostponementsPerCompleted ?? "—"}</td></tr>`).join("") || "<tr><td colspan=\"5\">لا توجد بيانات زمنية مكتملة لخطوات المتابعة بعد.</td></tr>";
  return `<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><style>@page{margin:22px}body{font-family:Arial,sans-serif;color:#172554;padding:20px;direction:rtl}h1{color:#4338CA;margin:0 0 6px}.meta{color:#64748B;font-size:12px;margin-bottom:18px}.metrics{display:flex;gap:10px;margin-bottom:18px}.metric{background:#FFF7ED;border:1px solid #FED7AA;border-radius:12px;flex:1;padding:12px}.value{color:#C2410C;font-size:22px;font-weight:700}.label{color:#64748B;font-size:11px;margin-top:3px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #E2E8F0;padding:9px;text-align:right;font-size:12px}th{background:#EEF2FF;color:#3730A3}.privacy{border-top:1px solid #E2E8F0;color:#64748B;font-size:11px;margin-top:22px;padding-top:12px}</style></head><body><h1>تقرير وقت خطوات المتابعة</h1><div class="meta">${escapeHtml(filterLabel)} · ${createdAt.toLocaleDateString("ar")}</div><div class="metrics"><div class="metric"><div class="value">${insights.length}</div><div class="label">مواد ذات بيانات</div></div><div class="metric"><div class="value">${measuredCompletions}</div><div class="label">إتمامات مقاسة</div></div><div class="metric"><div class="value">${postponements}</div><div class="label">مرات التأجيل</div></div></div><table><thead><tr><th>المادة</th><th>إتمامات مقاسة</th><th>متوسط وقت الإتمام</th><th>التأجيلات</th><th>تأجيل/إتمام</th></tr></thead><tbody>${rows}</tbody></table><p class="privacy">أُنشئ هذا التقرير محلياً من سجل خطوات المتابعة. لا يتضمن تسجيلات الصوت أو المرفقات أو نصوص الملاحظات.</p></body></html>`;
}
