import type { ReflectionFocusArea, WeeklyReflection } from "./study-types";
import { normalizeFollowUpDueAt, normalizeFollowUpPriority } from "./weekly-reflection-follow-up";

export const REFLECTION_FOCUS_AREAS: { id: ReflectionFocusArea; label: string }[] = [{ id: "review", label: "المراجعة" }, { id: "organization", label: "التنظيم" }, { id: "focus", label: "التركيز" }, { id: "wellbeing", label: "التوازن" }];
function normalizeRating(value: unknown): WeeklyReflection["rating"] { return typeof value === "number" && Number.isInteger(value) && value >= 1 && value <= 5 ? value as WeeklyReflection["rating"] : undefined; }
function normalizeFocusAreas(values: unknown): ReflectionFocusArea[] { const valid = new Set(REFLECTION_FOCUS_AREAS.map((area) => area.id)); return Array.isArray(values) ? Array.from(new Set(values.filter((value): value is ReflectionFocusArea => typeof value === "string" && valid.has(value as ReflectionFocusArea)))).slice(0, 4) : []; }
function normalizeFollowUpGoal(value: unknown) { return typeof value === "string" ? value.trim().slice(0, 140) : ""; }
function normalizeFollowUpSubjectId(value: unknown) { return typeof value === "string" && value.trim() ? value.trim().slice(0, 120) : undefined; }

export function normalizeWeeklyReflection(weekStart: string, note: string, attributesOrUpdatedAt: Partial<Pick<WeeklyReflection, "rating" | "focusAreas" | "followUpGoal" | "followUpCompleted" | "followUpCompletedAt" | "followUpPriority" | "followUpDueAt" | "followUpSubjectId">> | string = {}, updatedAt = new Date().toISOString()): WeeklyReflection { const attributes = typeof attributesOrUpdatedAt === "string" ? {} : attributesOrUpdatedAt; const timestamp = typeof attributesOrUpdatedAt === "string" ? attributesOrUpdatedAt : updatedAt; const followUpGoal = normalizeFollowUpGoal(attributes.followUpGoal); const followUpCompleted = Boolean(followUpGoal && attributes.followUpCompleted); return { weekStart, note: note.trim().slice(0, 1000), rating: normalizeRating(attributes.rating), focusAreas: normalizeFocusAreas(attributes.focusAreas), followUpGoal: followUpGoal || undefined, followUpCompleted, followUpCompletedAt: followUpCompleted ? attributes.followUpCompletedAt ?? timestamp : undefined, followUpPriority: followUpGoal ? normalizeFollowUpPriority(attributes.followUpPriority) : undefined, followUpDueAt: followUpGoal ? normalizeFollowUpDueAt(attributes.followUpDueAt) : undefined, followUpSubjectId: followUpGoal ? normalizeFollowUpSubjectId(attributes.followUpSubjectId) : undefined, updatedAt: timestamp }; }
