import type { Lecture, ReviewCard, ReviewList, Subject } from "@/lib/study-types";

const WEEK_MS = 7 * 24 * 60 * 60 * 1000;

function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character); }
function formatBytes(bytes: number) { if (!bytes) return "0 بايت"; const units = ["بايت", "ك.ب", "م.ب", "ج.ب"]; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}`; }

export function createWeeklySummaryReportHtml({ lectures, reviewCards, reviewLists = [], subjects, generatedAt = new Date() }: { lectures: Lecture[]; reviewCards: ReviewCard[]; reviewLists?: ReviewList[]; subjects: Subject[]; generatedAt?: Date }) {
  const now = generatedAt.getTime(); const weekStart = now - WEEK_MS;
  const weeklyLectures = lectures.filter((lecture) => new Date(lecture.recordedAt).getTime() >= weekStart);
  const reviewedCards = reviewCards.filter((card) => card.lastReviewedAt && new Date(card.lastReviewedAt).getTime() >= weekStart);
  const storage = weeklyLectures.reduce((sum, lecture) => sum + (lecture.audioSizeBytes ?? 0) + (lecture.attachments ?? []).reduce((attachmentSum, attachment) => attachmentSum + (attachment.sizeBytes ?? 0), 0), 0);
  const completedItems = reviewLists.reduce((sum, list) => sum + list.completedLectureIds.length, 0); const listItems = reviewLists.reduce((sum, list) => sum + list.lectureIds.length, 0);
  const rows = weeklyLectures.length ? weeklyLectures.map((lecture) => `<tr><td>${escapeHtml(lecture.title)}</td><td>${escapeHtml(subjects.find((subject) => subject.id === lecture.subjectId)?.title ?? "مادة")}</td><td>${new Date(lecture.recordedAt).toLocaleDateString("ar")}</td><td>${escapeHtml((lecture.tags ?? []).join("، ") || "—")}</td></tr>`).join("") : "<tr><td colspan=\"4\">لا توجد محاضرات جديدة خلال هذه الفترة.</td></tr>";
  return `<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="utf-8"/><style>@page{margin:24px}body{font-family:Arial,sans-serif;color:#172554;direction:rtl}h1{color:#312E81;margin:0 0 6px}.muted{color:#64748B;font-size:12px}.metrics{display:flex;gap:10px;margin:18px 0}.metric{background:#EEF2FF;border-radius:12px;flex:1;padding:12px}.metric strong{display:block;font-size:20px;margin-top:4px}table{width:100%;border-collapse:collapse;margin-top:12px}th{background:#312E81;color:#fff}th,td{border:1px solid #CBD5E1;padding:8px;text-align:right}tr:nth-child(even){background:#F8FAFC}.footer{margin-top:18px;color:#64748B;font-size:11px}</style></head><body><h1>موجز الأسبوع — مُحاضِر</h1><p class="muted">أُنشئ محلياً في ${escapeHtml(generatedAt.toLocaleString("ar"))}</p><section class="metrics"><div class="metric">محاضرات جديدة<strong>${weeklyLectures.length}</strong></div><div class="metric">بطاقات مراجعة<strong>${reviewedCards.length}</strong></div><div class="metric">حجم مضاف<strong>${formatBytes(storage)}</strong></div><div class="metric">إنجاز القوائم<strong>${completedItems}/${listItems}</strong></div></section><h2>محاضرات آخر 7 أيام</h2><table><thead><tr><th>المحاضرة</th><th>المادة</th><th>التاريخ</th><th>الوسوم</th></tr></thead><tbody>${rows}</tbody></table><p class="footer">هذا التقرير يعتمد على البيانات المحلية في مُحاضِر فقط، ولا يرسل معلومات الدراسة عند إنشائه أو مشاركته.</p></body></html>`;
}
