import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppHeader, EmptyState, LoadingView, PrimaryButton, StatusPill } from "@/components/study-ui";
import { appTheme } from "@/lib/app-theme";
import { useStudy } from "@/lib/study-context";
import type { ReviewCard } from "@/lib/study-types";
import { ScreenContainer } from "@/components/screen-container";

export default function ReviewScreen() {
  const router = useRouter();
  const { hydrated, reviewCards, reviewCard, getSubject, lectures } = useStudy();
  const [revealed, setRevealed] = useState<string | null>(null);
  if (!hydrated) return <ScreenContainer><LoadingView /></ScreenContainer>;
  const due = useMemo(() => reviewCards.filter((card) => new Date(card.dueAt).getTime() <= Date.now()).sort((a, b) => a.dueAt.localeCompare(b.dueAt)), [reviewCards]);
  const complete = (card: ReviewCard, correct: boolean) => { reviewCard(card.id, correct); setRevealed(null); };
  return <ScreenContainer className="px-5"><AppHeader eyebrow="تدريب قصير كل يوم" title="المراجعة" /><View style={styles.summary}><View style={styles.summaryIcon}><MaterialIcons name="style" size={25} color={appTheme.primary} /></View><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>{due.length ? `${due.length} بطاقة مستحقة اليوم` : "لا توجد بطاقات مستحقة الآن"}</Text><Text style={styles.summaryText}>أجب ثم أخبر التطبيق إن كنت تذكرت الإجابة ليضبط موعد المراجعة التالية.</Text></View></View><FlatList data={due} keyExtractor={(item) => item.id} contentContainerStyle={due.length ? styles.list : styles.emptyList} renderItem={({ item }) => { const lecture = lectures.find((entry) => entry.id === item.lectureId); return <View style={styles.card}><View style={styles.cardTop}><StatusPill label={getSubject(lecture?.subjectId ?? "")?.title ?? "محاضرة"} tone="primary" /><Pressable onPress={() => lecture && router.push({ pathname: "/lecture/[lectureId]", params: { lectureId: lecture.id } })}><MaterialIcons name="open-in-new" size={19} color={appTheme.muted} /></Pressable></View><Text style={styles.question}>{item.question}</Text>{revealed === item.id ? <><View style={styles.answer}><Text style={styles.answerLabel}>الإجابة</Text><Text style={styles.answerText}>{item.answer}</Text></View><View style={styles.actions}><Pressable onPress={() => complete(item, false)} style={styles.retry}><Text style={styles.retryText}>لم أتذكر</Text></Pressable><Pressable onPress={() => complete(item, true)} style={styles.success}><Text style={styles.successText}>تذكرت</Text></Pressable></View></> : <PrimaryButton label="إظهار الإجابة" icon="visibility" onPress={() => setRevealed(item.id)} />}</View>; }} ListEmptyComponent={<EmptyState icon="check-circle-outline" title="مراجعتك اليوم مكتملة" description="ستظهر البطاقات المضافة من ملخصات المحاضرات عند حلول موعدها." action={<PrimaryButton label="فتح المكتبة" icon="auto-stories" onPress={() => router.push("/library")} />} />} /></ScreenContainer>;
}

const styles = StyleSheet.create({ summary: { alignItems: "flex-start", backgroundColor: appTheme.primarySoft, borderRadius: 20, flexDirection: "row-reverse", gap: 12, marginBottom: 16, padding: 16 }, summaryIcon: { alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 15, height: 46, justifyContent: "center", width: 46 }, summaryCopy: { flex: 1 }, summaryTitle: { color: appTheme.ink, fontSize: 15, fontWeight: "800", textAlign: "right" }, summaryText: { color: appTheme.muted, fontSize: 12, lineHeight: 18, marginTop: 3, textAlign: "right" }, list: { gap: 12, paddingBottom: 24 }, emptyList: { flexGrow: 1, justifyContent: "center", paddingBottom: 30 }, card: { backgroundColor: appTheme.surface, borderColor: appTheme.border, borderRadius: 20, borderWidth: 1, gap: 16, padding: 17 }, cardTop: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between" }, question: { color: appTheme.ink, fontSize: 18, fontWeight: "800", lineHeight: 28, textAlign: "right" }, answer: { backgroundColor: "#F8FAFF", borderColor: "#C7D2FE", borderRadius: 14, borderWidth: 1, padding: 13 }, answerLabel: { color: appTheme.primary, fontSize: 12, fontWeight: "800", textAlign: "right" }, answerText: { color: appTheme.ink, fontSize: 14, lineHeight: 22, marginTop: 4, textAlign: "right" }, actions: { flexDirection: "row-reverse", gap: 9 }, retry: { alignItems: "center", backgroundColor: appTheme.dangerSoft, borderRadius: 13, flex: 1, justifyContent: "center", minHeight: 45 }, retryText: { color: appTheme.danger, fontSize: 14, fontWeight: "800" }, success: { alignItems: "center", backgroundColor: appTheme.success, borderRadius: 13, flex: 1, justifyContent: "center", minHeight: 45 }, successText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" } });
