import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { AppHeader, EmptyState, LoadingView, PrimaryButton, StatusPill } from "@/components/study-ui";
import { ScreenContainer } from "@/components/screen-container";
import { appTheme } from "@/lib/app-theme";
import { cancelReviewSessionReminder, scheduleReviewSessionReminder } from "@/lib/study-reminders";
import { useStudy } from "@/lib/study-context";
import { isReviewDue, type ReviewGrade } from "@/lib/review-scheduler";
import { createReviewSessionEndsAt, getRemainingReviewSeconds } from "@/lib/review-session-timer";
import type { ReviewCard } from "@/lib/study-types";

const TIMER_DURATIONS = [10, 15, 25, 45];
const BREAK_DURATIONS = [3, 5, 10];
const WEEK_MS = 7 * 24 * 60 * 60 * 1000;

export default function ReviewScreen() {
  const router = useRouter();
  const { hydrated, reviewCards, reviewLists, reviewSessions, reviewChallenges, subjects, createReviewList, toggleReviewListLecture, deleteReviewList, addReviewSession, createReviewChallenge, deleteReviewChallenge, gradeReviewCard, getSubject, lectures } = useStudy();
  const [revealed, setRevealed] = useState<string | null>(null);
  const [listTitle, setListTitle] = useState("");
  const [selectedLectureIds, setSelectedLectureIds] = useState<string[]>([]);
  const [sessionMinutes, setSessionMinutes] = useState(15);
  const [sessionSeconds, setSessionSeconds] = useState(15 * 60);
  const [timerRunning, setTimerRunning] = useState(false);
  const [timerBusy, setTimerBusy] = useState(false);
  const [timerEndsAt, setTimerEndsAt] = useState<number | undefined>();
  const [timerNotificationId, setTimerNotificationId] = useState<string | undefined>();
  const [breakSeconds, setBreakSeconds] = useState(0);
  const [breakRunning, setBreakRunning] = useState(false);
  const [breakMinutes, setBreakMinutes] = useState(5);
  const [challengeSubjectId, setChallengeSubjectId] = useState("");
  const [challengeTarget, setChallengeTarget] = useState("10");

  const due = useMemo(() => reviewCards.filter((card) => isReviewDue(card)).sort((a, b) => a.dueAt.localeCompare(b.dueAt)), [reviewCards]);
  const candidates = useMemo(() => lectures.filter((lecture) => !lecture.archivedAt).slice(0, 8), [lectures]);
  const weeklySessions = useMemo(() => (reviewSessions ?? []).filter((session) => new Date(session.completedAt).getTime() >= Date.now() - WEEK_MS), [reviewSessions]);
  const dailyFocus = useMemo(() => Array.from({ length: 7 }, (_, index) => {
    const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index));
    const sessions = (reviewSessions ?? []).filter((session) => new Date(session.completedAt).toDateString() === date.toDateString());
    return { label: date.toLocaleDateString("ar", { weekday: "short" }), minutes: sessions.reduce((total, session) => total + session.durationMinutes, 0) };
  }), [reviewSessions]);
  const monthlyFocus = useMemo(() => Array.from({ length: 28 }, (_, index) => {
    const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (27 - index));
    const minutes = (reviewSessions ?? []).filter((session) => new Date(session.completedAt).toDateString() === date.toDateString()).reduce((total, session) => total + session.durationMinutes, 0);
    return { label: String(date.getDate()), minutes, level: minutes === 0 ? 0 : minutes < 15 ? 1 : minutes < 30 ? 2 : 3 };
  }), [reviewSessions]);
  const activeFocusDays = dailyFocus.filter((day) => day.minutes > 0).length;
  const achievement = activeFocusDays >= 5 ? { title: "بطل التركيز", note: "حافظت على 5 أيام أو أكثر هذا الأسبوع.", tone: appTheme.success } : activeFocusDays >= 3 ? { title: "مراجع منتظم", note: "أتممت جلسات في 3 أيام هذا الأسبوع.", tone: appTheme.primary } : null;
  const challengeProgress = useMemo(() => (reviewChallenges ?? []).map((challenge) => ({ challenge, completed: reviewCards.filter((card) => card.lastReviewedAt && new Date(card.lastReviewedAt).getTime() >= Date.now() - WEEK_MS && lectures.find((lecture) => lecture.id === card.lectureId)?.subjectId === challenge.subjectId).length })), [lectures, reviewCards, reviewChallenges]);

  useEffect(() => {
    if (!timerRunning || !timerEndsAt) return;
    const update = () => setSessionSeconds(getRemainingReviewSeconds(timerEndsAt));
    update(); const interval = setInterval(update, 1000); return () => clearInterval(interval);
  }, [timerEndsAt, timerRunning]);
  useEffect(() => {
    if (!timerRunning || sessionSeconds !== 0) return;
    setTimerRunning(false); setTimerEndsAt(undefined); void cancelReviewSessionReminder(timerNotificationId); setTimerNotificationId(undefined);
    addReviewSession(sessionMinutes); setBreakSeconds(breakMinutes * 60); setBreakRunning(true);
    Alert.alert("وقت استراحة", `اكتملت جلسة المراجعة. بدأ مؤقت استراحة مدته ${breakMinutes} دقائق.`);
  }, [addReviewSession, breakMinutes, sessionMinutes, sessionSeconds, timerNotificationId, timerRunning]);
  useEffect(() => {
    if (!breakRunning || breakSeconds <= 0) return;
    const interval = setInterval(() => setBreakSeconds((seconds) => Math.max(0, seconds - 1)), 1000); return () => clearInterval(interval);
  }, [breakRunning, breakSeconds]);
  useEffect(() => {
    if (!breakRunning || breakSeconds !== 0) return;
    setBreakRunning(false); Alert.alert("انتهت الاستراحة", "عُد إلى جلسة مراجعة جديدة عندما تكون مستعداً.");
  }, [breakRunning, breakSeconds]);

  if (!hydrated) return <ScreenContainer><LoadingView /></ScreenContainer>;

  const complete = (card: ReviewCard, grade: ReviewGrade) => { gradeReviewCard(card.id, grade); setRevealed(null); };
  const toggleTimer = async () => {
    if (timerBusy) return; setTimerBusy(true);
    try {
      if (timerRunning) { const remaining = getRemainingReviewSeconds(timerEndsAt) || sessionSeconds; setSessionSeconds(remaining); setTimerEndsAt(undefined); setTimerRunning(false); await cancelReviewSessionReminder(timerNotificationId); setTimerNotificationId(undefined); return; }
      const seconds = sessionSeconds === 0 ? sessionMinutes * 60 : sessionSeconds;
      if (timerNotificationId) await cancelReviewSessionReminder(timerNotificationId);
      const notificationId = await scheduleReviewSessionReminder(seconds);
      setSessionSeconds(seconds); setTimerEndsAt(createReviewSessionEndsAt(seconds)); setTimerNotificationId(notificationId); setTimerRunning(true);
    } finally { setTimerBusy(false); }
  };
  const resetTimer = async () => { if (timerBusy) return; setTimerBusy(true); try { await cancelReviewSessionReminder(timerNotificationId); setTimerNotificationId(undefined); setTimerEndsAt(undefined); setTimerRunning(false); setSessionSeconds(sessionMinutes * 60); } finally { setTimerBusy(false); } };
  const chooseDuration = async (minutes: number) => { if (timerBusy) return; setTimerBusy(true); try { await cancelReviewSessionReminder(timerNotificationId); setTimerNotificationId(undefined); setTimerEndsAt(undefined); setTimerRunning(false); setSessionMinutes(minutes); setSessionSeconds(minutes * 60); } finally { setTimerBusy(false); } };
  const chooseBreakDuration = (minutes: number) => { setBreakMinutes(minutes); if (breakRunning) setBreakSeconds(minutes * 60); };
  const skipBreak = () => { setBreakRunning(false); setBreakSeconds(0); };
  const createChallenge = () => { const target = Number(challengeTarget); if (!challengeSubjectId) { Alert.alert("اختر مادة", "اختر المادة التي تريد تحديها أولاً."); return; } try { createReviewChallenge(challengeSubjectId, target); setChallengeTarget("10"); Alert.alert("تم إنشاء التحدي", "سيُحسب تقدمك من البطاقات التي تراجعها خلال آخر 7 أيام."); } catch (error) { Alert.alert("تعذر إنشاء التحدي", error instanceof Error ? error.message : "تحقق من العدد ثم حاول مرة أخرى."); } };
  const toggleSelected = (lectureId: string) => setSelectedLectureIds((current) => current.includes(lectureId) ? current.filter((id) => id !== lectureId) : [...current, lectureId]);
  const createList = () => { if (!selectedLectureIds.length) { Alert.alert("اختر محاضرة", "اختر محاضرة واحدة على الأقل لتكوين قائمة مراجعة."); return; } try { createReviewList(listTitle || `مراجعة ${new Date().toLocaleDateString("ar")}`, selectedLectureIds); setListTitle(""); setSelectedLectureIds([]); } catch (error) { Alert.alert("تعذر إنشاء القائمة", error instanceof Error ? error.message : "حاول مرة أخرى."); } };
  const duplicateList = (title: string, lectureIds: string[]) => { try { createReviewList(`${title} — نسخة`, lectureIds); } catch (error) { Alert.alert("تعذر تكرار القائمة", error instanceof Error ? error.message : "حاول مرة أخرى."); } };
  const removeList = (id: string, title: string) => Alert.alert("حذف قائمة المراجعة", `سيُحذف تنظيم «${title}» فقط، ولن تُحذف المحاضرات أو البطاقات.`, [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => deleteReviewList(id) }]);

  const header = <>
    <View style={styles.summary}><View style={styles.summaryIcon}><MaterialIcons name="style" size={25} color={appTheme.primary} /></View><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>{due.length ? `${due.length} بطاقة مستحقة اليوم` : "لا توجد بطاقات مستحقة الآن"}</Text><Text style={styles.summaryText}>أجب ثم قيّم سهولة التذكر ليضبط التطبيق موعد المراجعة التالية.</Text></View></View>
    <View style={styles.timerCard}><View><Text style={styles.timerLabel}>جلسة مراجعة مركزة</Text><Text style={styles.timerValue}>{formatTimer(sessionSeconds)}</Text></View><View style={styles.timerActions}><Pressable disabled={timerBusy} onPress={() => void resetTimer()} style={[styles.timerReset, timerBusy && styles.disabled]}><MaterialIcons name="refresh" size={18} color={appTheme.primary} /></Pressable><Pressable disabled={timerBusy} onPress={() => void toggleTimer()} style={[styles.timerStart, timerBusy && styles.disabled]}><MaterialIcons name={timerRunning ? "pause" : "play-arrow"} size={20} color="#FFFFFF" /><Text style={styles.timerStartText}>{timerBusy ? "يجري الحفظ" : timerRunning ? "إيقاف" : "ابدأ"}</Text></Pressable></View><View style={styles.timerDurations}>{TIMER_DURATIONS.map((minutes) => <Pressable key={minutes} disabled={timerBusy} onPress={() => void chooseDuration(minutes)} style={[styles.timerDuration, sessionMinutes === minutes && styles.timerDurationActive, timerBusy && styles.disabled]}><Text style={[styles.timerDurationText, sessionMinutes === minutes && styles.timerDurationTextActive]}>{minutes} د</Text></Pressable>)}</View><Text style={styles.breakLabel}>مدة الاستراحة التالية</Text><View style={styles.timerDurations}>{BREAK_DURATIONS.map((minutes) => <Pressable key={minutes} onPress={() => chooseBreakDuration(minutes)} style={[styles.timerDuration, breakMinutes === minutes && styles.timerDurationActive]}><Text style={[styles.timerDurationText, breakMinutes === minutes && styles.timerDurationTextActive]}>{minutes} د</Text></Pressable>)}</View></View>
    {breakRunning ? <View style={styles.breakCard}><View style={styles.sectionRow}><MaterialIcons name="free-breakfast" size={20} color={appTheme.success} /><Text style={styles.listTitle}>استراحة قصيرة</Text><Pressable onPress={skipBreak} style={styles.timerReset}><MaterialIcons name="close" size={18} color={appTheme.primary} /></Pressable></View><Text style={styles.sessionLogText}>تبقّى {formatTimer(breakSeconds)} قبل العودة للمراجعة.</Text></View> : null}
    <View style={styles.sessionLog}><View style={styles.sectionRow}><MaterialIcons name="timer" size={20} color={appTheme.success} /><Text style={styles.listTitle}>جلساتك هذا الأسبوع</Text><StatusPill label={`${weeklySessions.length} جلسة`} tone="success" /></View><Text style={styles.sessionLogText}>{weeklySessions.length ? `${weeklySessions.reduce((total, session) => total + session.durationMinutes, 0)} دقيقة تركيز مكتملة` : "تكتمل الجلسة عند وصول المؤقت إلى الصفر."}</Text></View>
    <View style={styles.sessionLog}><View style={styles.sectionRow}><MaterialIcons name="insights" size={20} color={appTheme.primary} /><Text style={styles.listTitle}>تركيزك اليومي</Text><StatusPill label={`${dailyFocus[6]?.minutes ?? 0} د اليوم`} tone="primary" /></View><View style={styles.timerDurations}>{dailyFocus.map((day, index) => <View key={`${day.label}-${index}`} style={styles.timerDuration}><Text style={styles.timerDurationText}>{day.label} {day.minutes}د</Text></View>)}</View></View>
    <View style={styles.sessionLog}><View style={styles.sectionRow}><MaterialIcons name="calendar-month" size={20} color={appTheme.violet} /><Text style={styles.listTitle}>خريطة التركيز — آخر 28 يوماً</Text></View><View style={styles.heatmap}>{monthlyFocus.map((day, index) => <View key={`${day.label}-${index}`} style={[styles.heatCell, day.level === 0 ? styles.heat0 : day.level === 1 ? styles.heat1 : day.level === 2 ? styles.heat2 : styles.heat3]}><Text style={[styles.heatLabel, day.level > 1 && styles.heatLabelActive]}>{day.label}</Text></View>)}</View><Text style={styles.heatmapHint}>كلما زادت كثافة اللون زادت دقائق التركيز في ذلك اليوم.</Text></View>
    {achievement ? <View style={styles.achievementCard}><MaterialIcons name="workspace-premium" size={28} color={achievement.tone} /><View style={styles.achievementCopy}><Text style={styles.achievementTitle}>{achievement.title}</Text><Text style={styles.achievementNote}>{achievement.note}</Text></View><StatusPill label={`${activeFocusDays} أيام`} tone="success" /></View> : <View style={styles.achievementHint}><MaterialIcons name="emoji-events" size={20} color={appTheme.warning} /><Text style={styles.achievementHintText}>أكمل جلسات في {Math.max(0, 3 - activeFocusDays)} أيام إضافية لتحصل على شارة «مراجع منتظم».</Text></View>}
    <View style={styles.listCard}><View style={styles.sectionRow}><MaterialIcons name="flag" size={21} color={appTheme.warning} /><Text style={styles.listTitle}>تحدي مراجعة حسب المادة</Text></View><Text style={styles.listHint}>ضع هدف بطاقات لمادة واحدة خلال آخر 7 أيام.</Text><View style={styles.options}>{subjects.slice(0, 8).map((subject) => <Pressable key={subject.id} onPress={() => setChallengeSubjectId(subject.id)} style={[styles.option, challengeSubjectId === subject.id && styles.optionSelected]}><MaterialIcons name={challengeSubjectId === subject.id ? "check-circle" : "radio-button-unchecked"} size={17} color={challengeSubjectId === subject.id ? appTheme.primary : appTheme.muted} /><Text style={[styles.optionText, challengeSubjectId === subject.id && styles.optionTextSelected]}>{subject.title}</Text></Pressable>)}</View><View style={styles.challengeControls}><TextInput value={challengeTarget} onChangeText={setChallengeTarget} keyboardType="number-pad" maxLength={3} textAlign="center" style={styles.challengeInput} /><Pressable onPress={createChallenge} style={styles.challengeButton}><Text style={styles.createButtonText}>بدء التحدي</Text></Pressable></View>{challengeProgress.map(({ challenge, completed }) => { const subject = getSubject(challenge.subjectId); const percent = Math.min(100, (completed / challenge.targetCards) * 100); return <View key={challenge.id} style={styles.challengeRow}><Pressable onPress={() => deleteReviewChallenge(challenge.id)} style={styles.deleteList}><MaterialIcons name="close" size={16} color={appTheme.danger} /></Pressable><View style={styles.challengeCopy}><View style={styles.sectionRow}><Text style={styles.listTitle}>{subject?.title ?? "مادة"}</Text><Text style={styles.challengeProgress}>{completed}/{challenge.targetCards}</Text></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${percent}%` }]} /></View></View></View>; })}</View>
    <View style={styles.listCard}><View style={styles.sectionRow}><MaterialIcons name="playlist-add-check" size={21} color={appTheme.violet} /><Text style={styles.listTitle}>قائمة مراجعة جديدة</Text></View><TextInput value={listTitle} onChangeText={setListTitle} placeholder="مثال: مراجعة قبل الاختبار" placeholderTextColor="#94A3B8" textAlign="right" returnKeyType="done" style={styles.listInput} /><Text style={styles.listHint}>اختر المحاضرات التي تريد إنهاءها ضمن جلسة واحدة.</Text><View style={styles.options}>{candidates.map((lecture) => <Pressable key={lecture.id} onPress={() => toggleSelected(lecture.id)} style={[styles.option, selectedLectureIds.includes(lecture.id) && styles.optionSelected]}><MaterialIcons name={selectedLectureIds.includes(lecture.id) ? "check-circle" : "radio-button-unchecked"} size={17} color={selectedLectureIds.includes(lecture.id) ? appTheme.primary : appTheme.muted} /><Text numberOfLines={1} style={[styles.optionText, selectedLectureIds.includes(lecture.id) && styles.optionTextSelected]}>{lecture.title}</Text></Pressable>)}</View><Pressable onPress={createList} style={styles.createButton}><MaterialIcons name="add-task" size={18} color="#FFFFFF" /><Text style={styles.createButtonText}>إنشاء القائمة ({selectedLectureIds.length})</Text></Pressable></View>
    {(reviewLists ?? []).map((list) => <ReviewListCard key={list.id} title={list.title} lectureIds={list.lectureIds} completedLectureIds={list.completedLectureIds} lectures={lectures} onToggle={(lectureId) => toggleReviewListLecture(list.id, lectureId)} onOpen={(lectureId) => router.push({ pathname: "/lecture/[lectureId]", params: { lectureId } })} onDuplicate={() => duplicateList(list.title, list.lectureIds)} onDelete={() => removeList(list.id, list.title)} />)}
  </>;
  return <ScreenContainer className="px-5"><AppHeader eyebrow="تدريب قصير كل يوم" title="المراجعة" /><FlatList data={due} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={header} renderItem={({ item }) => <ReviewCardView card={item} revealed={revealed === item.id} subject={getSubject(lectures.find((lecture) => lecture.id === item.lectureId)?.subjectId ?? "")?.title ?? "محاضرة"} onReveal={() => setRevealed(item.id)} onGrade={(grade) => complete(item, grade)} onOpen={() => router.push({ pathname: "/lecture/[lectureId]", params: { lectureId: item.lectureId } })} />} ListEmptyComponent={<EmptyState icon="check-circle-outline" title="مراجعتك اليوم مكتملة" description="أنشئ قائمة مراجعة من المحاضرات أو انتظر بطاقاتك التالية." action={<PrimaryButton label="فتح المكتبة" icon="auto-stories" onPress={() => router.push("/library")} />} />} /></ScreenContainer>;
}

function ReviewCardView({ card, subject, revealed, onReveal, onGrade, onOpen }: { card: ReviewCard; subject: string; revealed: boolean; onReveal: () => void; onGrade: (grade: ReviewGrade) => void; onOpen: () => void }) { return <View style={styles.card}><View style={styles.cardTop}><StatusPill label={subject} tone="primary" /><Pressable onPress={onOpen}><MaterialIcons name="open-in-new" size={19} color={appTheme.muted} /></Pressable></View><Text style={styles.question}>{card.question}</Text>{revealed ? <><View style={styles.answer}><Text style={styles.answerLabel}>الإجابة</Text><Text style={styles.answerText}>{card.answer}</Text></View><View style={styles.actions}>{([['again', 'مرة أخرى', 'retry'], ['hard', 'صعب', 'hard'], ['good', 'جيد', 'good'], ['easy', 'سهل', 'easy']] as const).map(([grade, label, tone]) => <Pressable key={grade} onPress={() => onGrade(grade)} style={[styles.gradeButton, styles[tone]]}><Text style={[styles.gradeText, (tone === "good" || tone === "easy") && styles.lightText]}>{label}</Text></Pressable>)}</View></> : <PrimaryButton label="إظهار الإجابة" icon="visibility" onPress={onReveal} />}</View>; }

function ReviewListCard({ title, lectureIds, completedLectureIds, lectures, onToggle, onOpen, onDuplicate, onDelete }: { title: string; lectureIds: string[]; completedLectureIds: string[]; lectures: ReturnType<typeof useStudy>["lectures"]; onToggle: (lectureId: string) => void; onOpen: (lectureId: string) => void; onDuplicate: () => void; onDelete: () => void }) { const completed = completedLectureIds.length; const percent = lectureIds.length ? Math.round((completed / lectureIds.length) * 100) : 0; return <View style={styles.savedList}><View style={styles.savedHeader}><Pressable onPress={onDelete} style={styles.deleteList}><MaterialIcons name="delete-outline" size={18} color={appTheme.danger} /></Pressable><Pressable onPress={onDuplicate} style={styles.copyList}><MaterialIcons name="content-copy" size={17} color={appTheme.primary} /></Pressable><View style={styles.savedCopy}><Text style={styles.savedTitle}>{title}</Text><Text style={styles.savedMeta}>{completed} من {lectureIds.length} محاضرات مكتملة</Text></View><View style={styles.doneBadge}><Text style={styles.doneBadgeText}>{percent}%</Text></View></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${percent}%` }]} /></View>{lectureIds.map((lectureId) => { const lecture = lectures.find((item) => item.id === lectureId); if (!lecture) return null; const done = completedLectureIds.includes(lectureId); return <Pressable key={lectureId} onPress={() => onToggle(lectureId)} style={styles.listLecture}><MaterialIcons name={done ? "check-circle" : "radio-button-unchecked"} size={20} color={done ? appTheme.success : appTheme.muted} /><Text style={[styles.listLectureText, done && styles.listLectureDone]}>{lecture.title}</Text><Pressable onPress={() => onOpen(lectureId)}><MaterialIcons name="open-in-new" size={17} color={appTheme.muted} /></Pressable></Pressable>; })}</View>; }
function formatTimer(seconds: number) { return `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`; }

const styles = StyleSheet.create({
  list: { gap: 12, paddingBottom: 24 }, summary: { alignItems: "flex-start", backgroundColor: appTheme.primarySoft, borderRadius: 20, flexDirection: "row-reverse", gap: 12, marginBottom: 12, padding: 16 }, summaryIcon: { alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 15, height: 46, justifyContent: "center", width: 46 }, summaryCopy: { flex: 1 }, summaryTitle: { color: appTheme.ink, fontSize: 15, fontWeight: "800", textAlign: "right" }, summaryText: { color: appTheme.muted, fontSize: 12, lineHeight: 18, marginTop: 3, textAlign: "right" },
  timerCard: { alignItems: "center", backgroundColor: "#F5F3FF", borderColor: "#DDD6FE", borderRadius: 19, borderWidth: 1, flexDirection: "row-reverse", flexWrap: "wrap", justifyContent: "space-between", marginBottom: 12, padding: 14 }, timerLabel: { color: appTheme.violet, fontSize: 12, fontWeight: "800", textAlign: "right" }, breakLabel: { color: appTheme.muted, fontSize: 11, fontWeight: "800", marginTop: 12, textAlign: "right", width: "100%" }, timerValue: { color: appTheme.ink, fontSize: 28, fontWeight: "800", marginTop: 3 }, timerActions: { flexDirection: "row-reverse", gap: 7 }, timerReset: { alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 11, height: 40, justifyContent: "center", width: 40 }, timerStart: { alignItems: "center", backgroundColor: appTheme.violet, borderRadius: 11, flexDirection: "row-reverse", gap: 3, justifyContent: "center", minWidth: 75, paddingHorizontal: 9 }, timerStartText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, timerDurations: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7, justifyContent: "flex-end", marginTop: 12, width: "100%" }, timerDuration: { backgroundColor: "#FFFFFF", borderColor: "#DDD6FE", borderRadius: 9, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 6 }, timerDurationActive: { backgroundColor: appTheme.violet, borderColor: appTheme.violet }, timerDurationText: { color: appTheme.violet, fontSize: 11, fontWeight: "800" }, timerDurationTextActive: { color: "#FFFFFF" }, disabled: { opacity: 0.5 },
  sessionLog: { backgroundColor: "#F0FDF4", borderColor: "#BBF7D0", borderRadius: 16, borderWidth: 1, gap: 7, marginBottom: 12, padding: 13 }, breakCard: { backgroundColor: "#FFF7ED", borderColor: "#FED7AA", borderRadius: 16, borderWidth: 1, gap: 7, marginBottom: 12, padding: 13 }, sessionLogText: { color: appTheme.success, fontSize: 12, fontWeight: "700", textAlign: "right" }, sectionRow: { alignItems: "center", flexDirection: "row-reverse", gap: 7 }, achievementCard: { alignItems: "center", backgroundColor: "#FFFBEB", borderColor: "#FDE68A", borderRadius: 16, borderWidth: 1, flexDirection: "row-reverse", gap: 10, marginBottom: 12, padding: 13 }, achievementCopy: { flex: 1 }, achievementTitle: { color: appTheme.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, achievementNote: { color: appTheme.muted, fontSize: 11, marginTop: 3, textAlign: "right" }, achievementHint: { alignItems: "center", backgroundColor: appTheme.warningSoft, borderRadius: 14, flexDirection: "row-reverse", gap: 8, marginBottom: 12, padding: 11 }, achievementHintText: { color: "#92400E", flex: 1, fontSize: 11, fontWeight: "700", textAlign: "right" },
  heatmap: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 5 }, heatCell: { alignItems: "center", borderRadius: 7, height: 29, justifyContent: "center", width: 29 }, heat0: { backgroundColor: "#DCFCE7" }, heat1: { backgroundColor: "#BBF7D0" }, heat2: { backgroundColor: "#4ADE80" }, heat3: { backgroundColor: "#15803D" }, heatLabel: { color: appTheme.success, fontSize: 9, fontWeight: "800" }, heatLabelActive: { color: "#FFFFFF" }, heatmapHint: { color: appTheme.muted, fontSize: 10, textAlign: "right" },
  listCard: { backgroundColor: "#F8FAFF", borderColor: "#C7D2FE", borderRadius: 19, borderWidth: 1, gap: 10, marginBottom: 12, padding: 14 }, listTitle: { color: appTheme.ink, flex: 1, fontSize: 15, fontWeight: "800", textAlign: "right" }, listInput: { backgroundColor: "#FFFFFF", borderColor: appTheme.border, borderRadius: 11, borderWidth: 1, color: appTheme.ink, fontSize: 13, minHeight: 42, paddingHorizontal: 11 }, listHint: { color: appTheme.muted, fontSize: 11, textAlign: "right" }, options: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, option: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: appTheme.border, borderRadius: 10, borderWidth: 1, flexDirection: "row-reverse", gap: 5, maxWidth: "100%", paddingHorizontal: 9, paddingVertical: 7 }, optionSelected: { backgroundColor: appTheme.primarySoft, borderColor: "#A5B4FC" }, optionText: { color: appTheme.muted, fontSize: 11, fontWeight: "700", maxWidth: 120 }, optionTextSelected: { color: appTheme.primary }, createButton: { alignItems: "center", backgroundColor: appTheme.primary, borderRadius: 12, flexDirection: "row-reverse", gap: 7, justifyContent: "center", minHeight: 43 }, createButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" },
  challengeControls: { flexDirection: "row-reverse", gap: 8 }, challengeInput: { backgroundColor: "#FFFFFF", borderColor: "#C7D2FE", borderRadius: 10, borderWidth: 1, color: appTheme.ink, fontSize: 13, fontWeight: "800", height: 42, width: 56 }, challengeButton: { alignItems: "center", backgroundColor: appTheme.primary, borderRadius: 10, flex: 1, justifyContent: "center" }, challengeRow: { alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 11, flexDirection: "row-reverse", gap: 8, padding: 9 }, challengeCopy: { flex: 1, gap: 7 }, challengeProgress: { color: appTheme.primary, fontSize: 11, fontWeight: "800" },
  savedList: { backgroundColor: appTheme.surface, borderColor: appTheme.border, borderRadius: 19, borderWidth: 1, gap: 10, marginBottom: 12, padding: 14 }, savedHeader: { alignItems: "center", flexDirection: "row-reverse", gap: 9 }, savedCopy: { flex: 1 }, savedTitle: { color: appTheme.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, savedMeta: { color: appTheme.muted, fontSize: 11, marginTop: 3, textAlign: "right" }, doneBadge: { alignItems: "center", backgroundColor: appTheme.successSoft, borderRadius: 9, justifyContent: "center", minWidth: 42, paddingHorizontal: 6, paddingVertical: 5 }, doneBadgeText: { color: appTheme.success, fontSize: 11, fontWeight: "800" }, deleteList: { alignItems: "center", backgroundColor: appTheme.dangerSoft, borderRadius: 9, height: 31, justifyContent: "center", width: 31 }, copyList: { alignItems: "center", backgroundColor: appTheme.primarySoft, borderRadius: 9, height: 31, justifyContent: "center", width: 31 }, progressTrack: { backgroundColor: "#E2E8F0", borderRadius: 99, height: 6, overflow: "hidden" }, progressFill: { backgroundColor: appTheme.success, borderRadius: 99, height: 6 }, listLecture: { alignItems: "center", backgroundColor: "#F8FAFC", borderRadius: 10, flexDirection: "row-reverse", gap: 8, padding: 9 }, listLectureText: { color: appTheme.ink, flex: 1, fontSize: 12, fontWeight: "700", textAlign: "right" }, listLectureDone: { color: appTheme.muted, textDecorationLine: "line-through" },
  card: { backgroundColor: appTheme.surface, borderColor: appTheme.border, borderRadius: 20, borderWidth: 1, gap: 16, padding: 17 }, cardTop: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between" }, question: { color: appTheme.ink, fontSize: 18, fontWeight: "800", lineHeight: 28, textAlign: "right" }, answer: { backgroundColor: "#F8FAFF", borderColor: "#C7D2FE", borderRadius: 14, borderWidth: 1, padding: 13 }, answerLabel: { color: appTheme.primary, fontSize: 12, fontWeight: "800", textAlign: "right" }, answerText: { color: appTheme.ink, fontSize: 14, lineHeight: 22, marginTop: 4, textAlign: "right" }, actions: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, gradeButton: { alignItems: "center", borderRadius: 13, flexGrow: 1, justifyContent: "center", minHeight: 44, minWidth: 64, paddingHorizontal: 8 }, retry: { backgroundColor: appTheme.dangerSoft }, hard: { backgroundColor: "#FEF3C7" }, good: { backgroundColor: appTheme.primary }, easy: { backgroundColor: appTheme.success }, gradeText: { color: appTheme.ink, fontSize: 12, fontWeight: "800" }, lightText: { color: "#FFFFFF" },
});
