import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import { AppHeader, StatusPill } from "@/components/study-ui";
import { appTheme } from "@/lib/app-theme";
import { ScreenContainer } from "@/components/screen-container";

export default function SettingsScreen() { return <ScreenContainer className="px-5"><AppHeader eyebrow="التحكم والخصوصية" title="الإعدادات" /><ScrollView contentContainerStyle={styles.content}><View style={styles.notice}><MaterialIcons name="verified-user" size={23} color={appTheme.success} /><View style={styles.noticeText}><Text style={styles.noticeTitle}>ملفاتك تحت سيطرتك</Text><Text style={styles.noticeBody}>يحفظ التطبيق بنية دراستك وتسجيلاتك محلياً. لا يبدأ التحويل إلى نص أو التلخيص إلا بطلبك.</Text></View></View><SettingRow icon="storage" title="حفظ محلي أولاً" detail="السنوات والمواد وسجل المحاضرات محفوظة على هذا الجهاز" status="مفعّل" /><SettingRow icon="auto-awesome" title="المعالجة الذكية" detail="تحويل صوت إلى نص وتلخيص منظم عند الطلب" status="عند الطلب" /><SettingRow icon="language" title="لغة الواجهة" detail="العربية واتجاه القراءة من اليمين إلى اليسار" status="العربية" /><View style={styles.footer}><Text style={styles.footerTitle}>مُحاضِر</Text><Text style={styles.footerText}>دفتر دراسي صوتي يساعدك على حفظ المحاضرة وفهمها ومراجعتها.</Text></View></ScrollView></ScreenContainer>; }
function SettingRow({ icon, title, detail, status }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; detail: string; status: string }) { return <View style={styles.row}><View style={styles.rowIcon}><MaterialIcons name={icon} size={21} color={appTheme.primary} /></View><View style={styles.rowText}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowDetail}>{detail}</Text></View><StatusPill label={status} tone="neutral" /></View>; }
const styles = StyleSheet.create({ content: { gap: 12, paddingBottom: 30 }, notice: { alignItems: "flex-start", backgroundColor: appTheme.successSoft, borderRadius: 19, flexDirection: "row-reverse", gap: 12, padding: 16 }, noticeText: { flex: 1 }, noticeTitle: { color: appTheme.success, fontSize: 15, fontWeight: "800", textAlign: "right" }, noticeBody: { color: "#476A64", fontSize: 12, lineHeight: 19, marginTop: 4, textAlign: "right" }, row: { alignItems: "center", backgroundColor: appTheme.surface, borderColor: appTheme.border, borderRadius: 18, borderWidth: 1, flexDirection: "row-reverse", gap: 11, padding: 14 }, rowIcon: { alignItems: "center", backgroundColor: appTheme.primarySoft, borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, rowText: { flex: 1 }, rowTitle: { color: appTheme.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, rowDetail: { color: appTheme.muted, fontSize: 11, lineHeight: 17, marginTop: 3, textAlign: "right" }, footer: { alignItems: "center", marginTop: 20, paddingHorizontal: 30 }, footerTitle: { color: appTheme.primary, fontSize: 17, fontWeight: "800" }, footerText: { color: appTheme.muted, fontSize: 12, lineHeight: 19, marginTop: 4, textAlign: "center" } });
